"""Add POS tables

Revision ID: 21addc6d28ca
Revises: d54715a8047d
Create Date: 2026-05-10 05:44:55.156763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21addc6d28ca'
down_revision = 'd54715a8047d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'AMOUNT', name='discounttype'), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('change_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', 'REFUNDED', name='salestatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('sale_id')
    )
    op.create_index(op.f('ix_sales_invoice_number'), 'sales', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_sales_sale_id'), 'sales', ['sale_id'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'CARD', 'TRANSFER', 'CREDIT', name='paymentmethod'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.sale_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=False)
    op.create_table('sale_returns',
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('return_number', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', 'REFUNDED', name='salestatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.sale_id'], ),
    sa.PrimaryKeyConstraint('return_id')
    )
    op.create_index(op.f('ix_sale_returns_return_id'), 'sale_returns', ['return_id'], unique=False)
    op.create_index(op.f('ix_sale_returns_return_number'), 'sale_returns', ['return_number'], unique=True)
    op.create_table('sale_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'AMOUNT', name='discounttype'), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_names.brand_id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.sale_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_sale_items_item_id'), 'sale_items', ['item_id'], unique=False)
    op.create_table('return_items',
    sa.Column('return_item_id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('sale_item_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_names.brand_id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['sale_returns.return_id'], ),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.item_id'], ),
    sa.PrimaryKeyConstraint('return_item_id')
    )
    op.create_index(op.f('ix_return_items_return_item_id'), 'return_items', ['return_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_return_items_return_item_id'), table_name='return_items')
    op.drop_table('return_items')
    op.drop_index(op.f('ix_sale_items_item_id'), table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index(op.f('ix_sale_returns_return_number'), table_name='sale_returns')
    op.drop_index(op.f('ix_sale_returns_return_id'), table_name='sale_returns')
    op.drop_table('sale_returns')
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_sales_sale_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_invoice_number'), table_name='sales')
    op.drop_table('sales')
    # ### end Alembic commands ###
