"""Add base tables

Revision ID: d54715a8047d
Revises: d6c7cf7f720b
Create Date: 2026-05-10 04:37:51.343041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd54715a8047d'
down_revision = 'd6c7cf7f720b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dosage_forms',
    sa.Column('dosage_form_id', sa.Integer(), nullable=False),
    sa.Column('form_code', sa.String(length=20), nullable=False),
    sa.Column('form_name', sa.String(length=100), nullable=False),
    sa.Column('form_category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('dosage_form_id')
    )
    op.create_index(op.f('ix_dosage_forms_dosage_form_id'), 'dosage_forms', ['dosage_form_id'], unique=False)
    op.create_index(op.f('ix_dosage_forms_form_code'), 'dosage_forms', ['form_code'], unique=True)
    op.create_table('manufacturers',
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_name', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='manufacturerstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('manufacturer_id')
    )
    op.create_index(op.f('ix_manufacturers_manufacturer_id'), 'manufacturers', ['manufacturer_id'], unique=False)
    op.create_table('therapeutic_classes',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_code', sa.String(length=20), nullable=False),
    sa.Column('class_name', sa.String(length=255), nullable=False),
    sa.Column('parent_class_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_class_id'], ['therapeutic_classes.class_id'], ),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_index(op.f('ix_therapeutic_classes_class_code'), 'therapeutic_classes', ['class_code'], unique=True)
    op.create_index(op.f('ix_therapeutic_classes_class_id'), 'therapeutic_classes', ['class_id'], unique=False)
    op.create_table('generic_drugs',
    sa.Column('generic_id', sa.Integer(), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=False),
    sa.Column('chemical_name', sa.String(length=500), nullable=True),
    sa.Column('molecular_formula', sa.String(length=100), nullable=True),
    sa.Column('cas_number', sa.String(length=20), nullable=True),
    sa.Column('therapeutic_class_id', sa.Integer(), nullable=True),
    sa.Column('pharmacology', sa.Text(), nullable=True),
    sa.Column('indications', sa.Text(), nullable=True),
    sa.Column('contraindications', sa.Text(), nullable=True),
    sa.Column('side_effects', sa.Text(), nullable=True),
    sa.Column('interactions', sa.Text(), nullable=True),
    sa.Column('pregnancy_category', sa.Enum('A', 'B', 'C', 'D', 'X', name='pregnancycategory'), nullable=True),
    sa.Column('controlled_substance_schedule', sa.Enum('CII', 'CIII', 'CIV', 'CV', 'NONE', name='controlledsubstanceschedule'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISCONTINUED', name='genericstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['therapeutic_class_id'], ['therapeutic_classes.class_id'], ),
    sa.PrimaryKeyConstraint('generic_id')
    )
    op.create_index(op.f('ix_generic_drugs_cas_number'), 'generic_drugs', ['cas_number'], unique=True)
    op.create_index(op.f('ix_generic_drugs_generic_id'), 'generic_drugs', ['generic_id'], unique=False)
    op.create_index(op.f('ix_generic_drugs_generic_name'), 'generic_drugs', ['generic_name'], unique=False)
    op.create_table('brand_names',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('generic_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('dosage_form_id', sa.Integer(), nullable=True),
    sa.Column('strength_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('strength_unit', sa.String(length=20), nullable=True),
    sa.Column('package_size', sa.String(length=50), nullable=True),
    sa.Column('ndc_number', sa.String(length=11), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('atc_code', sa.String(length=10), nullable=True),
    sa.Column('prescription_required', sa.Boolean(), nullable=True),
    sa.Column('storage_conditions', sa.Enum('ROOM_TEMPERATURE', 'REFRIGERATED', 'FROZEN', 'PROTECTED_FROM_LIGHT', name='storagecondition'), nullable=True),
    sa.Column('route_of_administration', sa.Enum('ORAL', 'INTRAVENOUS', 'INTRAMUSCULAR', 'SUBCUTANEOUS', 'TOPICAL', 'INHALATION', 'RECTAL', 'OPHTHALMIC', 'OTIC', 'NASAL', name='routeofadministration'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISCONTINUED', 'RECALLED', name='drugstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dosage_form_id'], ['dosage_forms.dosage_form_id'], ),
    sa.ForeignKeyConstraint(['generic_id'], ['generic_drugs.generic_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.manufacturer_id'], ),
    sa.PrimaryKeyConstraint('brand_id')
    )
    op.create_index(op.f('ix_brand_names_atc_code'), 'brand_names', ['atc_code'], unique=False)
    op.create_index(op.f('ix_brand_names_barcode'), 'brand_names', ['barcode'], unique=False)
    op.create_index(op.f('ix_brand_names_brand_id'), 'brand_names', ['brand_id'], unique=False)
    op.create_index(op.f('ix_brand_names_brand_name'), 'brand_names', ['brand_name'], unique=False)
    op.create_index(op.f('ix_brand_names_ndc_number'), 'brand_names', ['ndc_number'], unique=True)
    op.create_table('generic_alternatives',
    sa.Column('alternative_id', sa.Integer(), nullable=False),
    sa.Column('primary_generic_id', sa.Integer(), nullable=False),
    sa.Column('alternative_generic_id', sa.Integer(), nullable=False),
    sa.Column('bioequivalence_status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['alternative_generic_id'], ['generic_drugs.generic_id'], ),
    sa.ForeignKeyConstraint(['primary_generic_id'], ['generic_drugs.generic_id'], ),
    sa.PrimaryKeyConstraint('alternative_id')
    )
    op.create_index(op.f('ix_generic_alternatives_alternative_id'), 'generic_alternatives', ['alternative_id'], unique=False)
    op.create_table('drug_prices',
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('acquisition_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_names.brand_id'], ),
    sa.PrimaryKeyConstraint('price_id')
    )
    op.create_index(op.f('ix_drug_prices_price_id'), 'drug_prices', ['price_id'], unique=False)
    op.create_table('inventory',
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('current_quantity', sa.Integer(), nullable=True),
    sa.Column('minimum_quantity', sa.Integer(), nullable=True),
    sa.Column('maximum_quantity', sa.Integer(), nullable=True),
    sa.Column('reorder_quantity', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('manufacturing_date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'LOW_STOCK', 'OUT_OF_STOCK', 'EXPIRED', 'EXPIRING_SOON', name='inventorystatus'), nullable=True),
    sa.Column('last_restocked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_names.brand_id'], ),
    sa.PrimaryKeyConstraint('inventory_id'),
    sa.UniqueConstraint('brand_id')
    )
    op.create_index(op.f('ix_inventory_inventory_id'), 'inventory', ['inventory_id'], unique=False)
    op.create_table('inventory_alerts',
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('LOW_STOCK', 'OUT_OF_STOCK', 'EXPIRING_SOON', 'EXPIRED', name='alerttype'), nullable=False),
    sa.Column('threshold_value', sa.Integer(), nullable=True),
    sa.Column('current_value', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.inventory_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_inventory_alerts_alert_id'), 'inventory_alerts', ['alert_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('ADD', 'REMOVE', 'SALE', 'DAMAGE', 'ADJUSTMENT', name='movementtype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('previous_quantity', sa.Integer(), nullable=True),
    sa.Column('new_quantity', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.inventory_id'], ),
    sa.PrimaryKeyConstraint('movement_id')
    )
    op.create_index(op.f('ix_inventory_movements_movement_id'), 'inventory_movements', ['movement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_movements_movement_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_inventory_alerts_alert_id'), table_name='inventory_alerts')
    op.drop_table('inventory_alerts')
    op.drop_index(op.f('ix_inventory_inventory_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_drug_prices_price_id'), table_name='drug_prices')
    op.drop_table('drug_prices')
    op.drop_index(op.f('ix_generic_alternatives_alternative_id'), table_name='generic_alternatives')
    op.drop_table('generic_alternatives')
    op.drop_index(op.f('ix_brand_names_ndc_number'), table_name='brand_names')
    op.drop_index(op.f('ix_brand_names_brand_name'), table_name='brand_names')
    op.drop_index(op.f('ix_brand_names_brand_id'), table_name='brand_names')
    op.drop_index(op.f('ix_brand_names_barcode'), table_name='brand_names')
    op.drop_index(op.f('ix_brand_names_atc_code'), table_name='brand_names')
    op.drop_table('brand_names')
    op.drop_index(op.f('ix_generic_drugs_generic_name'), table_name='generic_drugs')
    op.drop_index(op.f('ix_generic_drugs_generic_id'), table_name='generic_drugs')
    op.drop_index(op.f('ix_generic_drugs_cas_number'), table_name='generic_drugs')
    op.drop_table('generic_drugs')
    op.drop_index(op.f('ix_therapeutic_classes_class_id'), table_name='therapeutic_classes')
    op.drop_index(op.f('ix_therapeutic_classes_class_code'), table_name='therapeutic_classes')
    op.drop_table('therapeutic_classes')
    op.drop_index(op.f('ix_manufacturers_manufacturer_id'), table_name='manufacturers')
    op.drop_table('manufacturers')
    op.drop_index(op.f('ix_dosage_forms_form_code'), table_name='dosage_forms')
    op.drop_index(op.f('ix_dosage_forms_dosage_form_id'), table_name='dosage_forms')
    op.drop_table('dosage_forms')
    # ### end Alembic commands ###
