"""Add inventory models

Revision ID: d6c7cf7f720b
Revises: 001_add_inventory
Create Date: 2026-05-10 04:27:34.015115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c7cf7f720b'
down_revision = '001_add_inventory'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_alerts_alert_id', table_name='inventory_alerts')
    op.drop_index('ix_inventory_alerts_inventory_id', table_name='inventory_alerts')
    op.drop_table('inventory_alerts')
    op.drop_index('ix_inventory_movements_inventory_id', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_movement_id', table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index('ix_inventory_brand_id', table_name='inventory')
    op.drop_index('ix_inventory_inventory_id', table_name='inventory')
    op.drop_table('inventory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('inventory_id', sa.INTEGER(), nullable=False),
    sa.Column('brand_id', sa.INTEGER(), nullable=False),
    sa.Column('current_quantity', sa.INTEGER(), nullable=True),
    sa.Column('minimum_quantity', sa.INTEGER(), nullable=True),
    sa.Column('maximum_quantity', sa.INTEGER(), nullable=True),
    sa.Column('reorder_quantity', sa.INTEGER(), nullable=True),
    sa.Column('batch_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('expiry_date', sa.DATETIME(), nullable=True),
    sa.Column('manufacturing_date', sa.DATETIME(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('last_restocked_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_names.brand_id'], ),
    sa.PrimaryKeyConstraint('inventory_id'),
    sa.UniqueConstraint('brand_id')
    )
    op.create_index('ix_inventory_inventory_id', 'inventory', ['inventory_id'], unique=False)
    op.create_index('ix_inventory_brand_id', 'inventory', ['brand_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('movement_id', sa.INTEGER(), nullable=False),
    sa.Column('inventory_id', sa.INTEGER(), nullable=False),
    sa.Column('movement_type', sa.VARCHAR(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('previous_quantity', sa.INTEGER(), nullable=True),
    sa.Column('new_quantity', sa.INTEGER(), nullable=True),
    sa.Column('reference_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('reference_id', sa.INTEGER(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('performed_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.inventory_id'], ),
    sa.PrimaryKeyConstraint('movement_id')
    )
    op.create_index('ix_inventory_movements_movement_id', 'inventory_movements', ['movement_id'], unique=False)
    op.create_index('ix_inventory_movements_inventory_id', 'inventory_movements', ['inventory_id'], unique=False)
    op.create_table('inventory_alerts',
    sa.Column('alert_id', sa.INTEGER(), nullable=False),
    sa.Column('inventory_id', sa.INTEGER(), nullable=False),
    sa.Column('alert_type', sa.VARCHAR(), nullable=False),
    sa.Column('threshold_value', sa.INTEGER(), nullable=True),
    sa.Column('current_value', sa.INTEGER(), nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_resolved', sa.BOOLEAN(), nullable=True),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.Column('resolved_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.inventory_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index('ix_inventory_alerts_inventory_id', 'inventory_alerts', ['inventory_id'], unique=False)
    op.create_index('ix_inventory_alerts_alert_id', 'inventory_alerts', ['alert_id'], unique=False)
    # ### end Alembic commands ###
